create_clock -period 10.000       [get_ports init_clk]
set_property PACKAGE_PIN G18      [get_ports init_clk]
set_property IOSTANDARD LVCMOS18  [get_ports init_clk]

set_property PACKAGE_PIN AN40 [get_ports gt_refclk_p]
set_property PACKAGE_PIN AN41 [get_ports gt_refclk_n]

set_property PACKAGE_PIN AU49 [get_ports {gt_txn[0]}]
set_property PACKAGE_PIN AU48 [get_ports {gt_txp[0]}]
set_property PACKAGE_PIN AU54 [get_ports {gt_rxn[0]}]
set_property PACKAGE_PIN AU53 [get_ports {gt_rxp[0]}]
set_property PACKAGE_PIN AT47 [get_ports {gt_txn[1]}]
set_property PACKAGE_PIN AT46 [get_ports {gt_txp[1]}]
set_property PACKAGE_PIN AT52 [get_ports {gt_rxn[1]}]
set_property PACKAGE_PIN AT51 [get_ports {gt_rxp[1]}]
set_property PACKAGE_PIN AR49 [get_ports {gt_txn[2]}]
set_property PACKAGE_PIN AR48 [get_ports {gt_txp[2]}]
set_property PACKAGE_PIN AR54 [get_ports {gt_rxn[2]}]
set_property PACKAGE_PIN AR53 [get_ports {gt_rxp[2]}]
set_property PACKAGE_PIN AR45 [get_ports {gt_txn[3]}]
set_property PACKAGE_PIN AR44 [get_ports {gt_txp[3]}]
set_property PACKAGE_PIN AP52 [get_ports {gt_rxn[3]}]
set_property PACKAGE_PIN AP51 [get_ports {gt_rxp[3]}]
